"""Report generator: qual_report.md + staged LaTeX rows (paper untouched)."""

from __future__ import annotations

import csv
import json
import statistics
from collections import defaultdict
from pathlib import Path

from qual_lib import registry

PROVISIONAL = {"MAPPO+Heb", "IPPO+Heb"}  # n=3 until extension seeds land
LABEL_ORDER = [lab for lab, _, _, _ in registry.CONDITIONS]


def _read_csv(path: Path) -> list:
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _num(v):
    try:
        f = float(v)
        return f
    except (TypeError, ValueError):
        return None


def _agg_by_label(rows, fields):
    """label -> {field: (mean, n)} over run-level rows."""
    by = defaultdict(lambda: defaultdict(list))
    for r in rows:
        for f in fields:
            v = _num(r.get(f))
            if v is not None:
                by[r["label"]][f].append(v)
    out = {}
    for lab, d in by.items():
        out[lab] = {f: (round(statistics.fmean(v), 3), len(v))
                    for f, v in d.items() if v}
    return out


def _md_table(header, rows):
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return out


def _fmt(agg, lab, field):
    v = agg.get(lab, {}).get(field)
    if not v:
        return "--"
    star = "*" if lab in PROVISIONAL else ""
    return f"{v[0]}{star}"


def run(args) -> int:
    T = args.out / "tables"
    comm = _read_csv(T / "comm_run_level.csv")
    soc = _read_csv(T / "social_interpretability.csv")
    bel = _read_csv(T / "beliefs.csv")
    fail = _read_csv(T / "failure_taxonomy_run_level.csv")
    bond_c = _read_csv(T / "bonds_behavior_condition.csv")
    tmpl = _read_csv(T / "comm_templates.csv")
    agreement = {}
    ap = args.out / "annotations" / "agreement.json"
    if ap.exists():
        agreement = json.loads(ap.read_text(encoding="utf-8"))

    labels_present = [lab for lab in LABEL_ORDER
                      if any(r["label"] == lab for r in comm)]

    L = ["# Qualitative analysis — medium suite",
         "",
         "Generated by `analysis_qualitative/run.py report` over the 65/66-run "
         "extended-seed suite (only exp06_ippo_hebbian/seed_1213 outstanding — "
         "rows marked `*` pool fewer than 6 runs). One run "
         "(exp11_llm_9b_allied_none/seed_456) is quarantined for step-keyed "
         "analyses (cross-job artifact contamination); it contributes nothing "
         "below.",
         ""]

    # coverage
    n_by_label = defaultdict(int)
    for r in comm:
        n_by_label[r["label"]] += 1
    L += ["## Coverage", ""]
    L += _md_table(["condition", "runs analyzed"],
                   [[lab, n_by_label.get(lab, 0)] for lab in labels_present])

    # dimension 1
    cf = ["msgs_per_100_steps", "dup_rate", "teammate_naming_rate",
          "object_naming_rate", "ch3_switch_talk", "ch3_chains",
          "ch3_silent_presses"]
    agg = _agg_by_label(comm, cf)
    L += ["", "## 1. Communication content (means over runs)", ""]
    L += _md_table(["condition"] + cf,
                   [[lab] + [_fmt(agg, lab, f) for f in cf]
                    for lab in labels_present])
    if tmpl:
        L += ["", "Top message templates per condition: "
              "`tables/comm_templates.csv`; per-chamber category mix: "
              "`tables/comm_categories.csv`."]

    # dimension 2
    if soc:
        sf = ["bond_ref_coverage", "faith_mae", "faith_within_005",
              "follow_same_step", "follow_window", "follow_baseline",
              "argmax_consistency", "ask_rate", "respond_follow"]
        agg = _agg_by_label(soc, sf)
        soc_labels = [lab for lab in labels_present if lab in agg]
        L += ["", "## 2. Social-module interpretability", "",
              "`follow_*` vs `follow_baseline` is the directive-follow lift "
              "(coupling is prompt-only, so <1.0 follow is meaningful).", ""]
        L += _md_table(["condition"] + sf,
                       [[lab] + [_fmt(agg, lab, f) for f in sf]
                        for lab in soc_labels])

    # dimension 3
    if fail:
        dets = sorted({k for r in fail for k in r
                       if k not in ("run", "label", "seed", "quarantined")})
        agg = _agg_by_label(fail, dets)
        L += ["", "## 3. Failure taxonomy (events per 1k team steps, "
              "mean over runs)", ""]
        L += _md_table(["condition"] + dets,
                       [[lab] + [_fmt(agg, lab, d) for d in dets]
                        for lab in labels_present])
        L += ["", "Flag records with provenance: `flags/flags.jsonl.gz` "
              "(feeds the annotation stage adjudication)."]

    # dimension 4
    if bel:
        bf = ["perception_grounding_rate", "partner_loc_accuracy",
              "partner_loc_claims", "belief_responsiveness",
              "contagion_rate"]
        agg = _agg_by_label(bel, bf)
        L += ["", "## 4. Beliefs & hallucination", ""]
        L += _md_table(["condition"] + bf,
                       [[lab] + [_fmt(agg, lab, f) for f in bf]
                        for lab in labels_present])

    # bonds vs behavior
    if bond_c:
        L += ["", "## 5. Do bonds track joint behaviour? "
              "(pooled Spearman rho, pair-episodes)", "",
              "Backs the appendix's pair-interaction-tensor promise. Computed "
              "from episode summaries directly (final_metrics coop_metrics is "
              "zeroed by the coop_eval nesting bug).", ""]
        cols = ["rho_messages", "rho_joint_dig", "rho_proximity",
                "n_messages", "agent2_msg_share"]
        hdr = ["condition"] + cols
        rows = []
        for r in bond_c:
            rows.append([r["label"]] + [r.get(c, "--") or "--" for c in cols])
        L += _md_table(hdr, rows)

    # annotations
    L += ["", "## Annotation status", ""]
    if agreement:
        for dim, rep in agreement.items():
            L.append(f"- **{dim}**: {rep['annotated']}/{rep['sampled']} "
                     f"annotated, kappa={rep['kappa']}")
    else:
        L.append("- not yet annotated — run `run.py sample`, annotate the "
                 "batches (Claude in-session, see `samples/RUBRICS.md`), then "
                 "`run.py validate`.")

    L += ["", "## Case studies", "",
          "Shortlist + transcripts under `cases/` (`shortlist.csv`; one "
          "`transcript.md` per archetype exemplar)."]

    rdir = args.out / "report"
    rdir.mkdir(parents=True, exist_ok=True)
    (rdir / "qual_report.md").write_text("\n".join(L), encoding="utf-8")

    # staged LaTeX (NOT copied into the paper)
    tex = ["% Staged qualitative tables — do NOT include until suite complete",
           "% -- social interpretability rows --"]
    if soc:
        agg = _agg_by_label(soc, ["bond_ref_coverage", "faith_mae",
                                  "follow_same_step", "follow_baseline",
                                  "argmax_consistency"])
        for lab in labels_present:
            if lab not in agg:
                continue
            a = agg[lab]

            def g(f):
                return f"{a[f][0]:.2f}" if f in a else "--"
            tex.append(f"{lab:<14} & {g('bond_ref_coverage')} & "
                       f"{g('faith_mae')} & {g('follow_same_step')} & "
                       f"{g('follow_baseline')} & "
                       f"{g('argmax_consistency')} \\\\")
    tex.append("% -- bonds-vs-behaviour rows --")
    for r in bond_c:
        tex.append(f"{r['label']:<14} & {r.get('rho_messages') or '--'} & "
                   f"{r.get('rho_joint_dig') or '--'} & "
                   f"{r.get('rho_proximity') or '--'} \\\\")
    (rdir / "tex" if False else rdir).mkdir(exist_ok=True)
    (rdir / "qual_tables.tex").write_text("\n".join(tex), encoding="utf-8")
    print(f"report done -> {rdir / 'qual_report.md'}")
    return 0
