#!/usr/bin/env python3
"""make_bond_behavior_fig.py — does the learned bond graph track behaviour?

For every learned-Hebbian condition, the qualitative pipeline's collab stage
computed Spearman rho between the bond weight W_ij and three pair behaviours
(directed messages, joint digging, proximity) over pair-episode records
(6 ordered pairs x 3 episodes x seeds; n=90-108 per condition).

This script visualizes those correlations:

  bond_behavior_correlation.pdf   three-panel dot plot, one panel per
                                  behaviour: pooled rho (large dot) + per-seed
                                  rho (small dots) per condition, zero line
  bond_behavior_rows.tex          LaTeX rows: pooled rho + per-seed mean±sd

Reading note for the caption: rho(messages) is partly mechanical — W growth
includes a communication bonus (delta_comm), so bonds following messages and
messages following bonds are confounded there. rho(joint dig) and
rho(proximity) have no such feedback term and are the cleaner behavioural
signals.

Usage:
  python make_bond_behavior_fig.py
  python make_bond_behavior_fig.py --out paper_assets_final_comparison
"""

from __future__ import annotations

import argparse
import csv
import statistics as st
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

TABLES = [Path("analysis_qualitative/out/tables"),
          Path("analysis_qualitative/out_gemma/tables")]

# Row order (top to bottom in the figure). Learned graphs only — the frozen
# arms are either uniform/zero W (rho undefined: Allied-all, No-bonds) or a
# hardcoded topology (Allied-pair), which answers a different question.
CONDITIONS = ["LLM-2B+Heb", "LLM-9B+Heb", "Gemma-E4B+Heb",
              "IPPO+Heb", "MAPPO+Heb"]

BEHAVIOURS = [("rho_messages", "Messages"),
              ("rho_joint_dig", "Joint digging"),
              ("rho_proximity", "Proximity")]

INK = "#374151"       # primary text
MUTED = "#9ca3af"     # axis/grid ink
ACCENT = "#2563eb"    # pooled rho
ACCENT_SOFT = "#93c5fd"  # per-seed dots


def load():
    pooled, seeds, n_pairs = {}, defaultdict(lambda: defaultdict(list)), {}
    for root in TABLES:
        cond = root / "bonds_behavior_condition.csv"
        if cond.is_file():
            for r in csv.DictReader(cond.open(encoding="utf-8")):
                lab = r["label"]
                n_pairs[lab] = int(float(r["n_messages"] or 0))
                pooled[lab] = {k: float(r[k]) if r.get(k) else None
                               for k, _ in BEHAVIOURS}
        runs = root / "bonds_behavior_runs.csv"
        if runs.is_file():
            for r in csv.DictReader(runs.open(encoding="utf-8")):
                if r.get("quarantined") == "True":
                    continue
                for k, _ in BEHAVIOURS:
                    if r.get(k):
                        seeds[r["label"]][k].append(float(r[k]))
    return pooled, seeds, n_pairs


def figure(pooled, seeds, n_pairs, out: Path):
    fig, axes = plt.subplots(1, 3, figsize=(9.0, 2.9), sharey=True)
    ys = range(len(CONDITIONS) - 1, -1, -1)  # first condition on top

    for ax, (key, title) in zip(axes, BEHAVIOURS):
        ax.axvline(0, color=MUTED, lw=1, zorder=1)
        for y, lab in zip(ys, CONDITIONS):
            for v in seeds.get(lab, {}).get(key, []):
                ax.plot(v, y, "o", ms=4.5, color=ACCENT_SOFT, mec="white",
                        mew=0.5, zorder=2)
            p = (pooled.get(lab) or {}).get(key)
            if p is not None:
                ax.plot(p, y, "o", ms=9, color=ACCENT, mec="white", mew=1.2,
                        zorder=3)
                ax.annotate(f"{p:+.2f}", (p, y), textcoords="offset points",
                            xytext=(0, 7), ha="center", fontsize=7.5,
                            color=INK)
        ax.set_title(title, fontsize=10, color=INK)
        ax.set_xlim(-0.55, 1.05)
        ax.set_xticks([-0.5, 0, 0.5, 1])
        ax.tick_params(colors=MUTED, labelsize=8.5)
        ax.grid(axis="x", color=MUTED, alpha=0.25, lw=0.6)
        for side in ("top", "right", "left"):
            ax.spines[side].set_visible(False)
        ax.spines["bottom"].set_color(MUTED)

    axes[0].set_yticks(list(ys))
    axes[0].set_yticklabels(CONDITIONS, fontsize=9, color=INK)
    axes[1].set_xlabel(r"Spearman $\rho$(bond weight $W_{ij}$, pair behaviour)"
                       "   —   large dot = pooled, small = per seed",
                       fontsize=8.5, color=INK)
    fig.tight_layout()
    fig.savefig(out / "bond_behavior_correlation.pdf", bbox_inches="tight")
    plt.close(fig)


def latex(pooled, seeds, n_pairs) -> str:
    L = ["% Generated by make_bond_behavior_fig.py — do not edit by hand.",
         "% cols: condition & n pair-eps & rho msgs (pooled / seed mean±sd)",
         "%       & rho joint dig & rho proximity",
         "% NOTE for caption: rho(messages) is partly mechanical — W growth",
         "% includes the comm bonus, so it is consistency, not causation.",
         ]
    for lab in CONDITIONS:
        cells = [lab, str(n_pairs.get(lab, "--"))]
        for key, _ in BEHAVIOURS:
            p = (pooled.get(lab) or {}).get(key)
            sv = seeds.get(lab, {}).get(key, [])
            if p is None or not sv:
                cells.append("--")
            else:
                sd = st.stdev(sv) if len(sv) > 1 else 0.0
                cells.append(f"${p:+.2f}$ (${st.mean(sv):+.2f} \\pm {sd:.2f}$)")
        L.append(" & ".join(cells) + " \\\\")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path,
                    default=Path("paper_assets_final_comparison"))
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    pooled, seeds, n_pairs = load()
    missing = [c for c in CONDITIONS if c not in pooled]
    if missing:
        print(f"[warn] no condition-level rows for: {', '.join(missing)}")

    figure(pooled, seeds, n_pairs, args.out)
    (args.out / "bond_behavior_rows.tex").write_text(latex(pooled, seeds, n_pairs),
                                                     encoding="utf-8")

    print(f"{'condition':16s}{'n':>6s}" +
          "".join(f"{t:>22s}" for _, t in BEHAVIOURS))
    for lab in CONDITIONS:
        line = f"{lab:16s}{n_pairs.get(lab, 0):>6d}"
        for key, _ in BEHAVIOURS:
            p = (pooled.get(lab) or {}).get(key)
            sv = seeds.get(lab, {}).get(key, [])
            sd = st.stdev(sv) if len(sv) > 1 else 0.0
            line += (f"{p:+.2f} ({st.mean(sv):+.2f}±{sd:.2f})".rjust(22)
                     if p is not None and sv else "--".rjust(22))
        print(line)
    print(f"wrote {args.out}/bond_behavior_correlation.pdf and "
          "bond_behavior_rows.tex")


if __name__ == "__main__":
    main()