"""Generate the combined RQ3 table: imposed vs. earned social structure.

One table for both RQ3 mechanisms:
  * Imposed structure — the frozen-topology conditions (Qwen3.5-9B, N=3,
    social-bias coupling; runs_from_daic/medium_runs/exp09/10/11), where the
    graph is hand-set and never updated;
  * Earned structure — the transplant experiment (N=6), where bonds and
    memories were formed by real Phase A experience (Gemma; Qwen rows appear
    when its Phase B lands).

Metrics (identical machinery to the other paper tables, imported from
make_results.py): task return with include_comm=False (physical reward,
message pay excluded — NOTE: the RQ1 table reports the include_comm=True
historical variant, so its task-return column is not directly comparable),
All % (of the 25 non-communication milestones), Coop % (of the 17
cooperative Ch2-5 milestones), both after the entry-honesty filter, pooled
per episode, mean ± population SD.

Partner preference P(message target = partner) is reported where a partner
is defined: the Allied-pair dyad 0<->1 (chance 0.50 at N=3) and every
transplant/shuffled pair (chance 0.20 at N=6). "--" elsewhere.

exp11 (No-bonds) seed_456 is excluded: cross-run contamination (see the
qualitative-pipeline quarantine); the reduced n is footnoted.

Usage:
    PYTHONPATH=src python src/mindforge/tools/make_rq3_table.py
Writes paper_assets_transplant/RQ3_STRUCTURE_TABLE.tex.
"""

import statistics as st
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "src"))

import make_results as mr  # noqa: E402
from mindforge.tools.analyze_wiring import (  # noqa: E402
    load_message_matrix,
    seatmate_preference,
)

OUT = Path("paper_assets_transplant/RQ3_STRUCTURE_TABLE.tex")

MEDIUM = Path("runs_from_daic/medium_runs")
TOPOLOGY = [
    # (label, dir, partner map or None, excluded seeds)
    ("No-bonds ($\\mathbf{W}\\equiv 0$)", "exp11_llm_9b_allied_none",
     None, frozenset({"exp11_llm_9b_allied_none/seed_456"})),
    ("Allied-pair ($0{\\leftrightarrow}1$ at $0.8$)",
     "exp10_llm_9b_allied_pair", {0: 1, 1: 0}, frozenset()),
    ("Allied-all (all pairs $0.8$)", "exp09_llm_9b_allied_all",
     None, frozenset()),
]

TRANSPLANT = [
    ("Gemma 4 E4B", Path("runs_from_daic/pair_bonding")),
    ("Qwen3.5-9B", Path("runs_from_daic/pair_bonding_qwen")),
]
ARMS = [("Transplant (real partners)", "expB_merged_transplant"),
        ("Shuffled (strangers)", "expB_merged_shuffled")]


def pmm(vals, nd):
    if not vals:
        return "--"
    return f"${st.fmean(vals):.{nd}f}$ \\pmm{{{st.pstdev(vals):.{nd}f}}}"


def perf_and_pref(runs_root, dir_name, n_agents, partner_map=None,
                  exclude=frozenset()):
    """Pooled per-episode task return / All% / Coop% / partner preference."""
    runs = mr.load_runs(runs_root, dir_name, exclude=exclude)
    if not runs:
        return None
    ret, ms, coop, pref = [], [], [], []
    for run in runs:
        r, _ = mr.episode_task_returns(run, include_comm=False)
        ret.extend(r)
        for team in mr.episode_milestone_sets(run):
            noncomm = sum(1 for m in team
                          if mr.MILESTONE_TRACK.get(m) != "communication")
            ms.append(100.0 * noncomm / mr.NONCOMM_MAX)
            coop.append(100.0 * mr.coop_count(team) / mr.COOP_MAX)
        if partner_map is not None or n_agents == 6:
            pm = partner_map  # None -> default seating (0-1, 2-3, 4-5)
            _, per_ep = load_message_matrix(Path(run["_path"]).parent,
                                            n_agents)
            for _ep, mat in sorted(per_ep.items()):
                prefs = seatmate_preference(mat, seat_of_partner=pm)
                agents = sorted(pm) if pm is not None else range(n_agents)
                vals = [prefs[i][0] for i in agents
                        if prefs[i][0] is not None]
                if vals:
                    pref.append(st.fmean(vals))
    return {"ret": ret, "ms": ms, "coop": coop, "pref": pref,
            "n_runs": len(runs), "n_eps": len(ms)}


def row(label, s, pref_note=""):
    if s is None:
        return f"{label} & -- & -- & -- & -- \\\\  % pending"
    p = pmm(s["pref"], 2) + pref_note if s["pref"] else "--"
    note = (f"  % {s['n_runs']} runs, {s['n_eps']} episodes")
    return (f"{label} & {pmm(s['ret'], 0)} & {pmm(s['ms'], 1)} & "
            f"{pmm(s['coop'], 1)} & {p} \\\\{note}")


def build():
    L = []
    L.append("% ─── RQ3 combined table: imposed vs. earned social structure ──")
    L.append("% Generated by src/mindforge/tools/make_rq3_table.py — regenerate,")
    L.append("% do not hand-edit. Same machinery as the other paper tables")
    L.append("% (make_results.py: team union per episode, entry-honesty filter,")
    L.append("% 25/17 denominators, include_comm=False task return, pooled")
    L.append("% episodes, population SD).")
    L.append("% Requires booktabs + makecell (+ \\pmm from floats.tex).")
    L.append("\\begin{table*}[t]")
    L.append("\\centering")
    L.append("\\caption{\\textbf{Imposed vs.\\ earned social structure "
             "(RQ3).} Top: frozen hand-set topologies (Qwen3.5-9B, $N{=}3$, "
             "social-bias coupling; graph read but never updated). Bottom: "
             "transplanted structure earned in Phase~A ($N{=}6$; see "
             "\\autoref{tab:transplant_main} for the per-pair breakdown). "
             "All values mean~$\\pm$~population SD over pooled episodes; "
             "\\emph{Task return} (team-summed physical reward, message pay "
             "excluded), \\emph{All} (\\% of the 25 non-communication "
             "milestones), \\emph{Coop.} (\\% of the 17 cooperative "
             "Ch2--Ch5 milestones), both after the entry-honesty filter. "
             "\\emph{Partner pref.} $=P(\\text{message target}=\\text{"
             "partner})$ where a partner is defined: the Allied-pair dyad "
             "(chance $0.50$ at $N{=}3$) and each transplanted pair, pooled "
             "per arm (chance $0.20$ at $N{=}6$). Transplant runs start in "
             "Chamber~3, so 12 of the 25 (and 4 of the 17 cooperative) "
             "milestones are structurally unreachable there: milestone "
             "percentages are comparable within a section, not across "
             "sections, and preferences are comparable to their own chance "
             "level. $^{\\dagger}$one No-bonds seed excluded (cross-run "
             "contamination), $n{=}5$ seeds.}")
    L.append("\\label{tab:rq3_structure}")
    L.append("\\footnotesize")
    L.append("\\setlength{\\tabcolsep}{4pt}")
    L.append("\\renewcommand{\\arraystretch}{1.15}")
    L.append("\\begin{tabular}{l c cc c}")
    L.append("\\toprule")
    L.append("& & \\multicolumn{2}{c}{Milestone \\%} & \\\\")
    L.append("\\cmidrule(lr){3-4}")
    L.append("Condition & Task return $\\uparrow$ & All $\\uparrow$ & "
             "Coop.\\ $\\uparrow$ & Partner pref. \\\\")
    L.append("\\midrule")
    L.append("\\multicolumn{5}{l}{\\emph{Imposed structure — frozen "
             "topologies (Qwen3.5-9B, $N{=}3$)}}\\\\")
    for label, dir_name, pm, excl in TOPOLOGY:
        s = perf_and_pref(MEDIUM, dir_name, 3, partner_map=pm, exclude=excl)
        lab = label + ("$^{\\dagger}$" if excl else "")
        L.append(row(lab, s))
        if s:
            print(f"  {dir_name}: runs={s['n_runs']} eps={s['n_eps']}",
                  file=sys.stderr)
    for model_name, root in TRANSPLANT:
        L.append("\\midrule")
        L.append(f"\\multicolumn{{5}}{{l}}{{\\emph{{Earned structure — "
                 f"transplanted pairs ({model_name}, $N{{=}}6$)}}}}\\\\")
        for arm_label, dir_name in ARMS:
            s = perf_and_pref(root, dir_name, 6) \
                if (root / dir_name).exists() else None
            L.append(row(arm_label, s))
            if s:
                print(f"  {model_name}/{dir_name}: runs={s['n_runs']} "
                      f"eps={s['n_eps']}", file=sys.stderr)
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table*}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    tex = build()
    OUT.write_text(tex, encoding="utf-8")
    print(f"wrote {OUT} ({len(tex.splitlines())} lines)")
