"""Generate the frozen-topology episode-horizon table (LaTeX).

Standalone remake of the old topology-horizon ablation table with the
paper's updated milestone machinery: raw per-episode team milestone COUNTS
become PERCENTAGES (All = % of the 25 non-communication milestones, Coop =
% of the 17 cooperative Ch2-5 milestones, both after the entry-honesty
filter), computed by the same make_results.py code paths as every other
table. Credit-Gini / excluded-share / episodes-completing columns are cut.

Task return stays the comm-INCLUSIVE undiffused environment reward
(include_comm=True) to remain comparable with the RQ1 medium table, which
these are the same runs as. (The transplant/RQ3 tables use the
comm-excluded variant; their captions say so.)

Design as in the original: both budgets on the same two seeds (42, 123;
n = 6 episodes per cell), because only those seeds were run at 2,000 steps.

Usage:
    PYTHONPATH=src python src/mindforge/tools/make_topology_horizon_table.py
Writes paper_assets_transplant/TOPOLOGY_HORIZON_TABLE.tex.
"""

import statistics as st
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "src"))

import make_results as mr  # noqa: E402

OUT = Path("paper_assets_transplant/TOPOLOGY_HORIZON_TABLE.tex")

SEEDS = {"seed_42", "seed_123"}   # the only seeds run at both budgets
BUDGETS = [("$1{,}000$", Path("runs_from_daic/medium_runs")),
           ("$2{,}000$", Path("runs_from_daic/medium_2k"))]
CONDITIONS = [
    ("No-bonds", "exp11_llm_9b_allied_none"),
    ("Allied-pair", "exp10_llm_9b_allied_pair"),
    ("Allied-all", "exp09_llm_9b_allied_all"),
]


def pmm(vals, nd):
    if not vals:
        return "--"
    return f"${st.fmean(vals):.{nd}f}$ \\pmm{{{st.pstdev(vals):.{nd}f}}}"


def cell_stats(runs_root, dir_name):
    """Pooled per-episode Coop% / All% / task return for seeds 42+123."""
    runs = [r for r in mr.load_runs(runs_root, dir_name)
            if Path(r["_path"]).parent.name in SEEDS]
    if not runs:
        return None
    ret, ms, coop = [], [], []
    for run in runs:
        r, _ = mr.episode_task_returns(run, include_comm=True)
        ret.extend(r)
        for team in mr.episode_milestone_sets(run):
            noncomm = sum(1 for m in team
                          if mr.MILESTONE_TRACK.get(m) != "communication")
            ms.append(100.0 * noncomm / mr.NONCOMM_MAX)
            coop.append(100.0 * mr.coop_count(team) / mr.COOP_MAX)
    return {"ret": ret, "ms": ms, "coop": coop,
            "n_runs": len(runs), "n_eps": len(ms)}


def build():
    L = []
    L.append("% ─── Frozen-topology episode-horizon table (percentages) ──")
    L.append("% Generated by src/mindforge/tools/make_topology_horizon_table.py")
    L.append("% — regenerate, do not hand-edit. Milestone %s via make_results")
    L.append("% machinery (team union per episode, entry-honesty filter, 25/17")
    L.append("% denominators, pooled episodes, population SD). Task return is")
    L.append("% comm-INCLUSIVE, matching the RQ1 medium table these runs share.")
    L.append("% Requires booktabs + makecell (+ \\pmm from floats.tex).")
    L.append("\\begin{table}[t]")
    L.append("\\centering")
    L.append("\\caption{\\textbf{Episode-horizon ablation of the frozen "
             "topologies (Qwen3.5-9B, social-bias coupling).} The three "
             "imposed graphs at $1{,}000$ vs.\\ $2{,}000$ steps, both "
             "budgets on the same two seeds ($42$, $123$; $n{=}6$ episodes "
             "per cell). Chamber timers scale with the budget, so completion "
             "percentages carry the signal, not the step of first firing. "
             "\\emph{Coop.} (\\% of the 17 cooperative Ch2--Ch5 "
             "milestones) and \\emph{All} (\\% of the 25 non-communication "
             "milestones), both team-union per episode after the "
             "entry-honesty filter; \\emph{Task return} (team-summed "
             "undiffused environment reward). Mean~$\\pm$~population SD "
             "over pooled episodes. The ordering across topologies inverts "
             "between horizons, but within the pooled standard deviation.}")
    L.append("\\label{tab:topology_horizon}")
    L.append("\\footnotesize")
    L.append("\\setlength{\\tabcolsep}{4pt}")
    L.append("\\renewcommand{\\arraystretch}{1.15}")
    L.append("\\begin{tabular}{l l ccc}")
    L.append("\\toprule")
    L.append("& & \\multicolumn{2}{c}{Milestone \\%} & \\\\")
    L.append("\\cmidrule(lr){3-4}")
    L.append("Condition & Steps & Coop.\\ $\\uparrow$ & All $\\uparrow$ & "
             "Task return $\\uparrow$ \\\\")
    L.append("\\midrule")
    for c_i, (label, dir_name) in enumerate(CONDITIONS):
        if c_i:
            L.append("\\addlinespace")
        for b_i, (steps, root) in enumerate(BUDGETS):
            s = cell_stats(root, dir_name)
            head = f"\\multirow{{2}}{{*}}{{{label}}}" if b_i == 0 else ""
            if s is None:
                L.append(f"{head} & {steps} & -- & -- & -- \\\\")
                continue
            L.append(f"{head} & {steps} & {pmm(s['coop'], 1)} & "
                     f"{pmm(s['ms'], 1)} & {pmm(s['ret'], 0)} \\\\")
            print(f"  {label:<12} {steps}: runs={s['n_runs']} "
                  f"eps={s['n_eps']}", file=sys.stderr)
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    tex = build()
    OUT.write_text(tex, encoding="utf-8")
    print(f"wrote {OUT} ({len(tex.splitlines())} lines)")
