"""Generate the transplant experiment main results table (LaTeX).

Mirrors the Experiment-2 cofire table conventions EXACTLY by importing the
same machinery from make_results.py rather than reimplementing it:

  * load_runs()                — episode slicing + entry-honesty filter
                                 (m20 needs m18, m24 needs m22, same-episode
                                 pre-filter team union; fake entry rewards
                                 are subtracted from the task stream);
  * episode_milestone_sets()   — team union per episode (post-filter);
  * episode_task_returns(include_comm=False)
                               — team physical reward per episode, message
                                 pay excluded;
  * NONCOMM_MAX (25) / COOP_MAX (17) denominators.

Aggregation: per-episode values pooled over ALL episodes of all seeds of a
condition (no per-seed averaging — every episode weighs equally), reported
as mean ± population SD (statistics.pstdev).

Partner-preference columns: per episode, each pair's preference is the mean
over its two agents of P(message target = partner) from that episode's
messages.jsonl; pooled the same way. Chance level at N=6 is 0.20.

Usage:
    PYTHONPATH=src python src/mindforge/tools/make_transplant_table.py
Writes paper_assets_transplant/TRANSPLANT_MAIN_TABLE.tex; Qwen rows appear
automatically when runs_from_daic/pair_bonding_qwen/expB_* exists, and as
placeholders otherwise.
"""

import statistics as st
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "src"))

import make_results as mr  # noqa: E402  (paper-table machinery)
from mindforge.tools.analyze_wiring import (  # noqa: E402
    load_message_matrix,
    seatmate_preference,
)

N_AGENTS = 6
PAIRS = [(0, 1), (2, 3), (4, 5)]

MODELS = [
    ("Gemma 4 E4B", Path("runs_from_daic/pair_bonding")),
    ("Qwen3.5-9B", Path("runs_from_daic/pair_bonding_qwen")),
]
ARMS = [("Transplant", "expB_merged_transplant"),
        ("Shuffled", "expB_merged_shuffled")]

OUT = Path("paper_assets_transplant/TRANSPLANT_MAIN_TABLE.tex")


def pooled(vals, nd):
    """mean ± population SD over pooled per-episode values, \\pmm-formatted."""
    if not vals:
        return "--"
    m, sd = st.fmean(vals), st.pstdev(vals)
    return f"${m:.{nd}f}$ \\pmm{{{sd:.{nd}f}}}"


def condition_stats(runs_root, dir_name):
    """Pool per-episode metrics over every completed seed of one condition."""
    runs = mr.load_runs(runs_root, dir_name)
    if not runs:
        return None
    vals = {"ret": [], "ms": [], "coop": [],
            "pref": {p: [] for p in PAIRS}}
    n_runs = 0
    for run in runs:
        n_runs += 1
        rets, _ = mr.episode_task_returns(run, include_comm=False)
        vals["ret"].extend(rets)
        for team in mr.episode_milestone_sets(run):
            noncomm = sum(1 for m in team
                          if mr.MILESTONE_TRACK.get(m) != "communication")
            vals["ms"].append(100.0 * noncomm / mr.NONCOMM_MAX)
            vals["coop"].append(100.0 * mr.coop_count(team) / mr.COOP_MAX)
        run_dir = Path(run["_path"]).parent
        _, per_ep = load_message_matrix(run_dir, N_AGENTS)
        for _ep, mat in sorted(per_ep.items()):
            prefs = seatmate_preference(mat)
            for a, b in PAIRS:
                pair_vals = [prefs[a][0], prefs[b][0]]
                pair_vals = [v for v in pair_vals if v is not None]
                if pair_vals:
                    vals["pref"][(a, b)].append(st.fmean(pair_vals))
    vals["n_runs"] = n_runs
    vals["n_eps"] = len(vals["ms"])
    return vals


def build():
    lines = []
    lines.append("% ─── Transplant experiment main results table ──")
    lines.append("% Generated by src/mindforge/tools/make_transplant_table.py")
    lines.append("% — regenerate, do not hand-edit. Mirrors the Experiment-2")
    lines.append("% conventions by importing make_results.py machinery")
    lines.append("% (team union per episode, entry-honesty filter, 25/17")
    lines.append("% denominators, pooled episodes, population SD).")
    lines.append("% Requires booktabs + makecell (+ the \\pmm macro from floats.tex).")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\caption{\\textbf{Pair transplant: do former partners still "
                 "wire together?} Six Phase~A agents per run, arranged as "
                 "three pairs; \\emph{Transplant} pairs each agent with its "
                 "real Phase~A partner, \\emph{Shuffled} with a stranger "
                 "carrying renamed memories of a history that never happened "
                 "(bonds and memory volume identical between arms). 3 seeds "
                 "$\\times$ 3 episodes per condition; all values "
                 "mean~$\\pm$~population SD over pooled episodes. \\emph{Task "
                 "return} (team-summed physical reward, message pay "
                 "excluded), \\emph{Milest.} (\\% of the 25 non-communication "
                 "milestones), \\emph{Coop.} (\\% of the 17 cooperative "
                 "Ch2--Ch5 milestones, both after the entry-honesty filter). "
                 "\\emph{Partner pref.}~$=P(\\text{message target}=\\text{"
                 "partner})$ per pair (chance $0.20$); in Transplant rows "
                 "pairs 1--2 co-fired in Phase~A and pair 3 is the "
                 "familiarity control (shared history, no co-fired "
                 "achievement); in Shuffled rows all three pairs are "
                 "strangers.}")
    lines.append("\\label{tab:transplant_main}")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4.5pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.2}")
    lines.append("\\begin{tabular}{l ccc ccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{Condition}")
    lines.append("& \\makecell{\\textbf{Task}\\\\\\textbf{return} $\\uparrow$}")
    lines.append("& \\makecell{\\textbf{Milest.}\\\\\\textbf{(\\%)} $\\uparrow$}")
    lines.append("& \\makecell{\\textbf{Coop.}\\\\\\textbf{(\\%)} $\\uparrow$}")
    lines.append("& \\makecell{\\textbf{Pref.}\\\\\\textbf{pair 1}}")
    lines.append("& \\makecell{\\textbf{Pref.}\\\\\\textbf{pair 2}}")
    lines.append("& \\makecell{\\textbf{Pref.}\\\\\\textbf{pair 3}} \\\\")
    for model_name, root in MODELS:
        lines.append("\\midrule")
        lines.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{model_name}}}}}\\\\")
        for arm_label, dir_name in ARMS:
            stats = condition_stats(root, dir_name) \
                if (root / dir_name).exists() else None
            if stats is None:
                lines.append(f"{arm_label} & -- & -- & -- & -- & -- & -- \\\\"
                             f"  % pending")
                continue
            cells = [
                pooled(stats["ret"], 0),
                pooled(stats["ms"], 1),
                pooled(stats["coop"], 1),
                *(pooled(stats["pref"][p], 2) for p in PAIRS),
            ]
            note = (f"  % {stats['n_runs']} runs, {stats['n_eps']} episodes"
                    if stats["n_runs"] != 3 or stats["n_eps"] != 9 else "")
            lines.append(f"{arm_label} & " + " & ".join(cells) + f" \\\\{note}")
            print(f"  {model_name:<12} {arm_label:<11} "
                  f"runs={stats['n_runs']} eps={stats['n_eps']}",
                  file=sys.stderr)
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    tex = build()
    OUT.write_text(tex, encoding="utf-8")
    print(f"wrote {OUT} ({len(tex.splitlines())} lines)")
